### ISSUE TITLE
Brief Question About Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [DirtyUnicorns/android_packages_services_Telephony#1]
Dear developers,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., com.android.internal.R). Your feedback will help to guide our research.
1. You used an internal interface in `TelephonyConnectionService` class of your project. Did you know that it is an internal interface of the Android library?
2. Are you aware that internal interfaces are unstable and may change without backward-compatibility?

Interface:  `com.android.internal.telephony.Phone`
File: [TelephonyConnectionService.java](https://github.com/DirtyUnicorns/android_packages_services_Telephony/blob/134bc5a5b22058ed76bb69e8f76c85885a517365/src/com/android/services/telephony/TelephonyConnectionService.java)
Line: 41

**Comment by JmzTaylor** [comment]
This file is untouched by us.  This file is completely Google and the AOSP Project.  Please direct your questions to them

**Comment by alinebrito** [comment]
ok, thanks for the feedback.
